force-app/main/default/objects/Lease_Agreement__c/Lease_Agreement__c.object-meta.xml
<CustomObject>
    <label>Lease Agreement</label>
    <nameField>
        <displayFormat>LEASE-{0000}</displayFormat>
        <label>Lease Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease_Agreement__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Lease Agreements</relationshipLabel>
    <relationshipName>Lease_Agreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tenant</label>
    <referenceTo>Tenant__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tenant__c/Tenant__c.object-meta.xml
<CustomObject>
    <label>Tenant</label>
    <nameField>
        <label>Tenant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LeaseExpiryReminder.cls
public class LeaseExpiryReminder implements Schedulable {
    public void execute(SchedulableContext sc) {
        List<Lease_Agreement__c> leaseExpiry = [
            SELECT Id, End_Date__c, Property__r.Tenant__r.Email__c, Property__r.Tenant__r.Name FROM Lease_Agreement__c 
            WHERE End_Date__c = :Date.today().addDays(30) AND Property__r.Tenant__r.Email__c != null
        ];

        System.debug(leaseExpiry.size());

        List<Messaging.SingleEmailMessage> messagesToSend = new List<Messaging.SingleEmailMessage>();

        for (Lease_Agreement__c lease : leaseExpiry) {
            String tenantEmail = lease.Property__r.Tenant__r.Email__c;
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

            mail.setToAddresses(new String[] {tenantEmail});
            mail.setSubject('Lease Expiration Notice');
            mail.setPlainTextBody('Dear '+ lease.Property__r.Tenant__r.Name + ', your lease expires on ' + lease.End_Date__c.format() + '.');
        
            //Add to the collection instead of sending immediately
            messagesToSend.add(mail);
        }

        if (!messagesToSend.isEmpty()) {
            try {
                Messaging.SendEmailResult[] results = Messaging.sendEmail(messagesToSend);

            } catch (Exception e) {
                System.debug('Error Sending bulk Messages: ' + e.getMessage());
            }   
        }
    }
}